# GitHub actions designed for the tests with modelica.
# On Linux, it is easy to automatically install OpenModelica,
# so we only test on Linux.

name: Modelica Tests
on: [push, pull_request]

jobs:
  job_1:
    runs-on: ${{ matrix.os }}
    name: Test
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    steps:
    - name: Checkout
      uses: actions/checkout@v1  # use the latest code commit

    - name: Setup conda with python ${{ matrix.python-version }}
      uses: s-weigand/setup-conda@v1.0.1

    - name: Install Python dependencies
      run: conda install pandas matplotlib conda-build

    - name: Install OpenModelica
      if: runner.os == 'Linux'  # This only works on Linux
      run: |
        # Installation instructions based on:
        # https://www.openmodelica.org/download/download-linux

        # Add sources for packaged openmodelica
        for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt `lsb_release -cs` release"; done | sudo tee /etc/apt/sources.list.d/openmodelica.list
        # You will also need to import the GPG key used to sign the releases:
        wget -q http://build.openmodelica.org/apt/openmodelica.asc -O - | sudo apt-key add -
        # To verify that your key is installed correctly
        apt-key fingerprint

        # Then update and install OpenModelica
        sudo apt update
        sudo apt install openmodelica
        #sudo apt install omlib-.* # Installs optional Modelica libraries (most have not been tested with OpenModelica)

    - name: Install AixLib
      if: runner.os == 'Linux'  # Only required on Linux
      run: |
        cd /usr/lib/omlibrary/  # cd to OpenModelica library
        wget -q https://github.com/RWTH-EBC/AixLib/archive/v0.9.1.tar.gz -O - | sudo tar xzf -
        sudo mv AixLib-0.9.1/AixLib/ 'AixLib 0.9.1'  # extract library from git folder
        sudo rm -r AixLib-0.9.1  # remove git folder
        cd /home/runner/work/modelicatest/modelicatest  # cd back to repo folder

    - name: Install OMPython
      # run: python -m pip install -U https://github.com/OpenModelica/OMPython/archive/master.zip
      run: python -m pip install -U https://github.com/OpenModelica/OMPython/archive/v3.0.3.zip

    - name: Run the first test for CHP
      run: python ./hp_debugging.py -m HeatGenerators.CHP.CHP
    - name: Run the second test for heatpump
      run: python ./hp_debugging.py -m HeatGenerators.HeatPump.HeatPump

    - name: Lint with flake8
      if: runner.os == 'Linux'  # Only needs to run once
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
